# This is a basic workflow to help you get started with Actions

name: Build student version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install nbgrader
    # TODO: replace with simpler solution
    - name: Get changes
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Create local changes
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          assignment=$(echo ${changed_file} | awk -F "/" '/^source/{ print $2 }')
          if [ -n ${assignment} ]
          then
            nbgrader generate_assignment ${assignment}
          fi
        done
    - name: Commit files
      # See SETUP.md for docs
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        COURSE_ID: '<COURSE_ID>'
        SOURCE_BEFORE_DIRECTORY: ''
        # Needs to be set in for loop
        SOURCE_DIRECTORY: ''
        DESTINATION_GITHUB_USERNAME: '<DESTINATION_GITHUB_USERNAME>'
        # Needs to be set in for loop
        DESTINATION_REPOSITORY_NAME: ''
        USER_EMAIL: '2039nslcs+github-actions[bot]@users.noreply.github.com'
        GITHUB_SERVER: 'github.com'
        USER_NAME: 'github-actions[bot]'
        DESTINATION_REPOSITORY_USERNAME: '<DESTINATION_REPOSITORY_USERNAME>'
        TARGET_BRANCH: main
        COMMIT_MESSAGE: 'chore: update assignment'
        TARGET_DIRECTORY: ''
      run: |
        # make file runnable, might not be necessary
        chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"
        for changed_file in ${{ steps.files.outputs.all }}; do
          assignment=$(echo ${changed_file} | awk -F "/" '/^source/{ print $2 }')
          if [ -n ${assignment} ]
          then
            SOURCE_DIRECTORY="release/${assignment}"
            DESTINATION_REPOSITORY_NAME="${COURSE_ID}-${assignment}"
            FINAL_COMMIT_MESSAGE="$COMMIT_MESSAGE ${assignment}"
            # run script
            "${GITHUB_WORKSPACE}/.github/script.sh" \
              "${SOURCE_BEFORE_DIRECTORY}" \
              "${SOURCE_DIRECTORY}" \
              "${DESTINATION_GITHUB_USERNAME}" \
              "${DESTINATION_REPOSITORY_NAME}" \
              "${GITHUB_SERVER}" \
              "${USER_EMAIL}" \
              "${USER_NAME}" \
              "${DESTINATION_REPOSITORY_USERNAME}" \
              "${TARGET_BRANCH}" \
              "${FINAL_COMMIT_MESSAGE}" \
              "${TARGET_DIRECTORY}"
          fi
        done
